# Generated by Django 3.0.8 on 2020-09-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofileform',
            name='height',
            field=models.IntegerField(blank=True),
        ),
    ]
