# Generated by Django 3.0.8 on 2020-09-22 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_gympicture_gymprofileform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=10)),
                ('clientData', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.ClientProfileForm')),
                ('gymData', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.GymProfileForm')),
                ('gymPictures', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.GymPicture')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
