# Generated by Django 3.0.8 on 2020-09-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_profilemaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GymPicture',
            new_name='GymPictureForm',
        ),
    ]
