# Generated by Django 3.0.8 on 2020-09-22 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200922_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemaster',
            name='clientData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ClientProfileForm'),
        ),
        migrations.AlterField(
            model_name='profilemaster',
            name='gymData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.GymProfileForm'),
        ),
        migrations.AlterField(
            model_name='profilemaster',
            name='gymPictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.GymPictureForm'),
        ),
    ]
