# Generated by Django 3.0.8 on 2020-09-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200922_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofileform',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clientprofileform',
            name='houseNo',
        ),
        migrations.RemoveField(
            model_name='clientprofileform',
            name='state',
        ),
    ]
