# Generated by Django 3.0.8 on 2020-09-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200926_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofileform',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
