# Generated by Django 3.0.8 on 2020-09-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_profilemaster_gympictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymprofileform',
            name='IFSCcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='accountNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='additionalInfo',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='bankBranch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='bankName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='closedOn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='closingTime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='facility',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='genders',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='openingTime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='speciality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='testimonial',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
