# Generated by Django 3.0.8 on 2020-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200929_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymprofileform',
            name='halfyearlyPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymprofileform',
            name='monthlyPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymprofileform',
            name='quarterlyPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymprofileform',
            name='yearlyPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
