# Generated by Django 3.0.8 on 2020-10-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_clientsubscriptionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscriptionform',
            name='startDate',
            field=models.DateField(),
        ),
    ]
