# Generated by Django 3.0.8 on 2020-10-01 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0015_auto_20201001_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=1000)),
                ('gatewayName', models.CharField(max_length=1000)),
                ('responseMsg', models.CharField(max_length=1000)),
                ('bankName', models.CharField(max_length=1000)),
                ('paymentMode', models.CharField(max_length=1000)),
                ('mid', models.CharField(max_length=1000)),
                ('responseCode', models.CharField(max_length=1000)),
                ('txnId', models.CharField(max_length=1000)),
                ('txnAmount', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('bankTxnId', models.CharField(max_length=1000)),
                ('txnDate', models.CharField(max_length=1000)),
                ('checksumHash', models.CharField(max_length=1000)),
                ('gymId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProfileMaster')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
