# Generated by Django 3.0.8 on 2020-10-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20201002_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentform',
            name='subData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.ClientSubscriptionForm'),
            preserve_default=False,
        ),
    ]
