# Generated by Django 3.0.8 on 2020-10-03 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0019_auto_20201002_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranferRequestForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiningDate', models.DateField()),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('newGymId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newGym', to='home.GymProfileForm')),
                ('oldGymId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldGym', to='home.GymProfileForm')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
