# Generated by Django 3.0.8 on 2020-10-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20201004_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsubscriptionform',
            name='paymentId',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.PaymentForm'),
        ),
    ]
