# Generated by Django 3.0.8 on 2020-10-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20201004_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietChartForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProfileMaster')),
            ],
        ),
    ]
