# Generated by Django 3.0.8 on 2020-10-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_dietchartform'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietchartform',
            name='day1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietchartform',
            name='day2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietchartform',
            name='day3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
