# Generated by Django 3.0.8 on 2020-10-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20201004_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietchartform',
            name='day4',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietchartform',
            name='day6',
            field=models.CharField(default=11, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietchartform',
            name='day7',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dietchartform',
            name='day1',
            field=models.CharField(max_length=1000),
        ),
    ]
