# Generated by Django 3.0.8 on 2020-10-05 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0028_timeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='likes',
        ),
        migrations.AddField(
            model_name='timeline',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
