# Generated by Django 3.0.8 on 2020-10-15 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20201005_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutChartForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('detail', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ProfileMaster')),
            ],
        ),
    ]
