# Generated by Django 3.0.8 on 2020-10-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_applyform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymprofileform',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='gymprofileform',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='gymprofileform',
            name='speciality',
        ),
    ]
