# Generated by Django 3.0.8 on 2020-10-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20201021_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(blank=True, max_length=10000)),
                ('genders', models.CharField(blank=True, max_length=100)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('ac', models.BooleanField(blank=True)),
                ('changingRoom', models.BooleanField(blank=True)),
                ('personalTrainer', models.BooleanField(blank=True)),
                ('sauna', models.BooleanField(blank=True)),
                ('locker', models.BooleanField(blank=True)),
                ('trainer', models.BooleanField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='featuresId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.GymFeatures'),
            preserve_default=False,
        ),
    ]
