# Generated by Django 3.0.8 on 2020-10-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20201021_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymfeatures',
            name='trainer',
        ),
    ]
