# Generated by Django 3.0.8 on 2020-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20201021_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofileform',
            name='height',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientprofileform',
            name='weight',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
