# Generated by Django 3.0.8 on 2020-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20201028_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietchartform',
            old_name='day4',
            new_name='dietCategory',
        ),
        migrations.RemoveField(
            model_name='dietchartform',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='dietchartform',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='dietchartform',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='dietchartform',
            name='day5',
        ),
        migrations.RemoveField(
            model_name='dietchartform',
            name='day6',
        ),
        migrations.RemoveField(
            model_name='dietchartform',
            name='day7',
        ),
        migrations.RemoveField(
            model_name='dietchartform',
            name='time',
        ),
        migrations.RemoveField(
            model_name='workoutchartform',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='workoutchartform',
            name='title',
        ),
        migrations.AddField(
            model_name='dietchartform',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutchartform',
            name='workoutCategory',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
