# Generated by Django 3.0.8 on 2020-11-26 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20201127_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietchartform',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='workoutchartform',
            name='userId',
        ),
    ]
