# Generated by Django 3.0.8 on 2020-11-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_gymprofileform_ytlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymprofileform',
            name='ytlink',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
