# Generated by Django 3.0.8 on 2020-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20201127_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymprofileform',
            name='halfyearlyOriginal',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='monthlyOriginal',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='quarterlyOriginal',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='gymprofileform',
            name='yearlyOriginal',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
