# Generated by Django 3.0.8 on 2020-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_ourservicesimagesandroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservicesimagesandroid',
            name='serviceName',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
