# Generated by Django 3.0.8 on 2021-03-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_ourservicesimagesandroid_servicename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymprofileform',
            name='halfyearlyOriginal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gymprofileform',
            name='monthlyOriginal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gymprofileform',
            name='quarterlyOriginal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='gymprofileform',
            name='yearlyOriginal',
            field=models.IntegerField(blank=True),
        ),
    ]
