# Generated by Django 3.0.8 on 2021-03-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210316_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymZumba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=5000)),
                ('fee', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='gymfeatures',
            name='zumba',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
