# Generated by Django 3.0.8 on 2021-03-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20210329_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymzumba',
            name='gymFeatureId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.GymFeatures'),
            preserve_default=False,
        ),
    ]
