# Generated by Django 3.2 on 2021-05-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_gymzumba_gymfeatureid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymzumba',
            name='image',
        ),
        migrations.CreateModel(
            name='GymZumbaImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('zumbaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gymzumba')),
            ],
        ),
    ]
